// eslint-disable-next-line no-unused-vars
const abi = [
  'constructor(tuple(address governor, address pauseGuardian, address baseToken, address baseTokenPriceFeed, address extensionDelegate, uint64 kink, uint64 perYearInterestRateSlopeLow, uint64 perYearInterestRateSlopeHigh, uint64 perYearInterestRateBase, uint64 reserveRate, uint64 storeFrontPriceFactor, uint64 trackingIndexScale, uint64 baseTrackingSupplySpeed, uint64 baseTrackingBorrowSpeed, uint104 baseMinForRewards, uint104 baseBorrowMin, uint104 targetReserves, tuple(address asset, address priceFeed, uint8 decimals, uint64 borrowCollateralFactor, uint64 liquidateCollateralFactor, uint64 liquidationFactor, uint128 supplyCap)[] assetConfigs) config)',
  'error Absurd()',
  'error AlreadyInitialized()',
  'error BadAsset()',
  'error BadDecimals()',
  'error BadDiscount()',
  'error BadKink()',
  'error BadMinimum()',
  'error BadPrice()',
  'error BadReserveRate()',
  'error BorrowCFTooLarge()',
  'error BorrowTooSmall()',
  'error InsufficientReserves()',
  'error InvalidInt104()',
  'error InvalidInt256()',
  'error InvalidUInt104()',
  'error InvalidUInt128()',
  'error InvalidUInt64()',
  'error LiquidateCFTooLarge()',
  'error NegativeNumber()',
  'error NoSelfTransfer()',
  'error NotCollateralized()',
  'error NotForSale()',
  'error NotLiquidatable()',
  'error Paused()',
  'error SupplyCapExceeded()',
  'error TimestampTooLarge()',
  'error TooManyAssets()',
  'error TooMuchSlippage()',
  'error TransferInFailed()',
  'error TransferOutFailed()',
  'error Unauthorized()',
  'event AbsorbCollateral(address indexed absorber, address indexed borrower, address indexed asset, uint128 collateralAbsorbed, uint256 usdValue)',
  'event AbsorbDebt(address indexed absorber, address indexed borrower, uint104 debtAbsorbed, uint256 usdValue)',
  'event BuyCollateral(address indexed buyer, address indexed asset, uint256 baseAmount, uint256 collateralAmount)',
  'event PauseAction(bool supplyPaused, bool transferPaused, bool withdrawPaused, bool absorbPaused, bool buyPaused)',
  'event Supply(address indexed from, address indexed dst, uint256 amount)',
  'event SupplyCollateral(address indexed from, address indexed dst, address indexed asset, uint256 amount)',
  'event Transfer(address indexed from, address indexed to, uint256 amount)',
  'event TransferCollateral(address indexed from, address indexed to, address indexed asset, uint256 amount)',
  'event Withdraw(address indexed src, address indexed to, uint256 amount)',
  'event WithdrawCollateral(address indexed src, address indexed to, address indexed asset, uint256 amount)',
  'event WithdrawReserves(address indexed to, uint256 amount)',
  'function absorb(address absorber, address[] accounts)',
  'function accrueAccount(address account)',
  'function approveThis(address manager, address asset, uint256 amount)',
  'function balanceOf(address account) view returns (uint256)',
  'function baseBorrowMin() view returns (uint256)',
  'function baseMinForRewards() view returns (uint256)',
  'function baseScale() view returns (uint256)',
  'function baseToken() view returns (address)',
  'function baseTokenPriceFeed() view returns (address)',
  'function baseTrackingBorrowSpeed() view returns (uint256)',
  'function baseTrackingSupplySpeed() view returns (uint256)',
  'function borrowBalanceOf(address account) view returns (uint256)',
  'function buyCollateral(address asset, uint256 minAmount, uint256 baseAmount, address recipient)',
  'function decimals() view returns (uint8)',
  'function extensionDelegate() view returns (address)',
  'function getAssetInfo(uint8 i) view returns (tuple(uint8 offset, address asset, address priceFeed, uint64 scale, uint64 borrowCollateralFactor, uint64 liquidateCollateralFactor, uint64 liquidationFactor, uint128 supplyCap))',
  'function getAssetInfoByAddress(address asset) view returns (tuple(uint8 offset, address asset, address priceFeed, uint64 scale, uint64 borrowCollateralFactor, uint64 liquidateCollateralFactor, uint64 liquidationFactor, uint128 supplyCap))',
  'function getBorrowRate(uint256 utilization) view returns (uint64)',
  'function getPrice(address priceFeed) view returns (uint128)',
  'function getReserves() view returns (int256)',
  'function getSupplyRate(uint256 utilization) view returns (uint64)',
  'function getUtilization() view returns (uint256)',
  'function governor() view returns (address)',
  'function hasPermission(address owner, address manager) view returns (bool)',
  'function initializeStorage()',
  'function isAbsorbPaused() view returns (bool)',
  'function isAllowed(address, address) view returns (bool)',
  'function isBorrowCollateralized(address account) view returns (bool)',
  'function isBuyPaused() view returns (bool)',
  'function isLiquidatable(address account) view returns (bool)',
  'function isSupplyPaused() view returns (bool)',
  'function isTransferPaused() view returns (bool)',
  'function isWithdrawPaused() view returns (bool)',
  'function kink() view returns (uint256)',
  'function liquidatorPoints(address) view returns (uint32 numAbsorbs, uint64 numAbsorbed, uint128 approxSpend, uint32 _reserved)',
  'function numAssets() view returns (uint8)',
  'function pause(bool supplyPaused, bool transferPaused, bool withdrawPaused, bool absorbPaused, bool buyPaused)',
  'function pauseGuardian() view returns (address)',
  'function perSecondInterestRateBase() view returns (uint256)',
  'function perSecondInterestRateSlopeHigh() view returns (uint256)',
  'function perSecondInterestRateSlopeLow() view returns (uint256)',
  'function quoteCollateral(address asset, uint256 baseAmount) view returns (uint256)',
  'function reserveRate() view returns (uint256)',
  'function storeFrontPriceFactor() view returns (uint256)',
  'function supply(address asset, uint256 amount)',
  'function supplyFrom(address from, address dst, address asset, uint256 amount)',
  'function supplyTo(address dst, address asset, uint256 amount)',
  'function targetReserves() view returns (uint256)',
  'function totalBorrow() view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function totalsCollateral(address) view returns (uint128 totalSupplyAsset, uint128 _reserved)',
  'function trackingIndexScale() view returns (uint256)',
  'function transfer(address dst, uint256 amount) returns (bool)',
  'function transferAsset(address dst, address asset, uint256 amount)',
  'function transferAssetFrom(address src, address dst, address asset, uint256 amount)',
  'function transferFrom(address src, address dst, uint256 amount) returns (bool)',
  'function userBasic(address) view returns (int104 principal, uint64 baseTrackingIndex, uint64 baseTrackingAccrued, uint16 assetsIn, uint8 _reserved)',
  'function userCollateral(address, address) view returns (uint128 balance, uint128 _reserved)',
  'function userNonce(address) view returns (uint256)',
  'function withdraw(address asset, uint256 amount)',
  'function withdrawFrom(address src, address to, address asset, uint256 amount)',
  'function withdrawReserves(address to, uint256 amount)',
  'function withdrawTo(address to, address asset, uint256 amount)',
];
