service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: proposal_117_monitor_market_entered
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}

  # Configure this section and rename secret-example.yml to secrets.yml
  name: Proposal 117 Monitor Market Entered
  # Comment out any secret that you do not want to be overwritten in Defender
  defenderSecrets:
    # Private variables pulled from external secrets.yml file
    discordWebhook: ${self:custom.stackSecrets.discordWebhook}
    slackWebhook: ${self:custom.stackSecrets.slackWebhook}

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Serverless Autotask
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: true
    relayer: ${self:resources.Resources.relayers.relayer-1}

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true

    secrets:
      stack: ${self:custom.defenderSecrets}

    relayers:
      relayer-1:
        name: ${self:custom.name} Serverless Relay
        network: mainnet
        min-balance: 100000000000000000

plugins:
  - defender-serverless
