service: generated-service
configValidationMode: error
frameworkVersion: 3

provider:
  name: defender
  stage: dev
  stackName: forta_large_delegations
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}
  discordWebhook: ${self:custom.stackSecrets.discordWebhook}
  name: Forta Large Delegations

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  filter:
    name: ${self:custom.name} Filter
    trigger:
      type: schedule
      frequency: 0
    paused: true
    path: autotask-1

resources:
  Resources:
    notifications:
      discord:
        type: discord
        name: ${self:custom.name} Discord
        config:
          url: ${self:custom.discordWebhook}
        paused: false
    sentinels:
      monitor:
        name: ${self:custom.name} Monitor
        type: FORTA
        network: mainnet
        paused: false
        notify-config:
          timeout: 0
          message: [TX]({{ metadata.transactionLink }}) {{ metadata.message }}
          message-subject: Defender Alert: ${self:custom.name}
          channels:
            - ${self:resources.Resources.notifications.discord}
        autotask-condition: ${self:functions.filter}
        conditions:
          min-scanner-count: 1
          severity: 1
          alert-ids:
            - AE-COMP-GOVERNANCE-DELEGATE-THRESHOLD
        agent-ids:
          - 0x0d3cdcc2757cd7837e3b302a9889c854044a80835562dc8060d7c163fbb69d53
plugins:
  - defender-serverless
