service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_low_liquidity
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  name: Forta Low Liquidity

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Filter
    path: autotask-1
    trigger:
      type: sentinel
    paused: false

resources:
  Resources:
    sentinels:
      sentinel-1:
        name: ${self:custom.name} Sentinel
        type: FORTA
        addresses: []
        network: mainnet
        paused: false
        notify-config:
          timeout: 0
          message: '[TX]({{ metadata.transactionLink }}) {{ metadata.message }}'
          message-subject: 'Defender Sentinel: Forta Low Liquidity Attack Monitor triggered'
          channels:
            - >-
              ${self:resources.Resources.notifications.security-alerts-liquidity-monitor}
        conditions:
          min-scanner-count: 1
          severity: 1
          alert-ids: []
        autotask-condition: ${self:functions.autotask-1}
        agent-ids: 0xe49ab07879658c258d5007ac6b88428a2b88cc5cfef206222ad94690840be87a

plugins:
  - defender-serverless
