service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_low_liquidity
  ssot: false

custom:
  config:  ${file(../secrets.yml)}
  name: Forta Low Liquidity
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}
  discordWebhook: ${self:custom.stackSecrets.discordWebhook}

  # Forta Sentinel Settings
  alert-ids:
    - AE-COMP-MARKET-ATTACK-EVENT
  agent-ids:
    - "0xe49ab07879658c258d5007ac6b88428a2b88cc5cfef206222ad94690840be87a"


defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Serverless Autotask Filter
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true
    notifications:
      security-alerts:
        type: discord
        name: SecurityAlerts
        config:
          url: >-
            https://discord.com/api/webhooks/974392977583669348/vD_9OBLHB0eYf0loRNXe5Eu9uR4Y5DVngxgtQ-Dde6ac36Zob7jqb56hlamf1dBWDqdy
        paused: false
      discord:
        type: discord
        name: '${self:custom.name} Security Alerts'
        config:
          url: ${self:custom.discordWebhook}
        paused: false
    sentinels:
      sentinel-1:
        name: ${self:custom.name} Serverless Sentinel
        type: FORTA
        addresses: []
        network: mainnet
        paused: false
        notify-config:
          timeout: 0
          message: '[TX]({{ metadata.transactionLink }}) {{ metadata.message }}'
          message-subject: 'Defender Sentinel: Forta Low Liquidity Attack Monitor triggered'
          channels:
            - ${self:resources.Resources.notifications.security-alerts}
        autotask-condition: ${self:functions.autotask-1}
        conditions:
          min-scanner-count: 1
          severity: 1
          alert-ids: ${self:custom.alert-ids}
        agent-ids: ${self:custom.agent-ids}

plugins:
  - defender-serverless
