service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_low_liquidity
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  name: Forta Low Liquidity
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}
  discordWebhook: ${self:custom.stackSecrets.discordWebhook}

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Filter
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    notifications:
      discord:
        type: discord
        name: "${self:custom.name} Discord Channel"
        config:
          url: ${self:custom.discordWebhook}
        paused: false
    sentinels:
      sentinel-1:
        name: ${self:custom.name} Sentinel
        type: FORTA
        addresses: []
        network: mainnet
        paused: false
        notify-config:
          timeout: 0
          message: "[TX]({{ metadata.transactionLink }}) {{ metadata.message }}"
          message-subject: "Defender Sentinel: Forta Low Liquidity triggered"
          channels:
            - ${self:resources.Resources.notifications.discord}
        autotask-condition: ${self:functions.autotask-1}
        conditions:
          min-scanner-count: 1
          severity: 1
          alert-ids: 
            - AE-COMP-MARKET-ATTACK-EVENT
        agent-ids:
          - "0xe49ab07879658c258d5007ac6b88428a2b88cc5cfef206222ad94690840be87a"

plugins:
  - defender-serverless