service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_v2_liquidation_monitor_dev
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}

  # Configure this section and rename secret-example.yml to secrets.yml
  name: Forta v2 Liquidation Monitor DEV

  # Forta Sentinel Settings
  alert-ids: [] # Accept all alerts
  agent-ids:
    - "0x3c61101f1d349661298a58ba59a58fbce5a3626c5c7af10b091796969e0d6c59"

  # Comment out any secret that you do not want to be overwritten in Defender
  defenderSecrets:
    # Private variables pulled from external secrets.yml file
    discordWebhook: ${self:custom.stackSecrets.discordWebhook}

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Serverless Autotask
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true

    secrets:
      stack: ${self:custom.defenderSecrets}

    relayers:

    sentinels:
      sentinel-1:
        name: ${self:custom.name} Serverless Sentinel
        type: FORTA
        addresses: []
        network: mainnet
        paused: false
        autotask-trigger: ${self:functions.autotask-1}
        notify-config:
          timeout: 0
          channels: []
        conditions:
          min-scanner-count: 1
          severity: 1
          alert-ids: ${self:custom.alert-ids}
        agent-ids: ${self:custom.agent-ids}

plugins:
  - defender-serverless
