service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_large_borrows_governance
  ssot: false

custom:
  config: ${file(../secrets.yml)}
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}
  discordWebhook: ${self:custom.stackSecrets.discordWebhook}
  name: Forta Large Borrows Governance

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Action
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    notifications:
      discord:
        type: discord
        name: ${self:custom.name} Discord
        config:
          url: ${self:custom.discordWebhook}
        paused: false
    sentinels:
      monitor:
        name: ${self:custom.name} Serverless Sentinel
        type: FORTA
        network: mainnet
        paused: false
        autotask-trigger: ${self:functions.autotask-1}
        notify-config:
          timeout: 0
          message: [TX]({{ metadata.transactionLink }}) {{ metadata.message }}
          message-subject: Defender Alert: ${self:custom.name}
          channels:
            - ${self:resources.Resources.notifications.discord}
        conditions:
          min-scanner-count: 1
          severity: 1
           alert-ids:
             - AE-COMP-GOVERNANCE-THRESHOLD
        agent-ids: 
          - 0xb6bdedbae67cc82e60aad02a8ffab3ccbefeaa876ca7e4f291c07c798a95e339

plugins:
  - defender-serverless
