service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: governance_twitter_bot
  ssot: false

# Configure and rename secret-example.yml to secrets.yml
custom:
  config: ${file(../secrets.yml)}
  # Compound Governance Address
  governanceAddress: "0xc0Da02939E1441F497fd74F78cE7Decb17B66529"

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: Compound Governance Twitter Serverless Autotask
    path: autotask-1
    trigger:
      type: schedule
      frequency: 52560000
    paused: false

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true

    secrets:
      stack:
        webhookURL: ${self:custom.config.secrets.webhookURL}

plugins:
  - defender-serverless
