service: generated-service
configValidationMode: error
frameworkVersion: "3"

provider:
  name: defender
  stage: dev
  stackName: forta_multi_sig
  ssot: false

custom:
  config:  ${file(../secrets.yml)}
  name: Forta Multi-Sig
  stackSecrets: ${self:custom.config.secrets.${self:provider.stackName}}
  discordWebhook: ${self:custom.stackSecrets.discordWebhook}

defender:
  key: ${self:custom.config.keys.api}
  secret: ${self:custom.config.keys.secret}

functions:
  autotask-1:
    name: ${self:custom.name} Filter
    path: autotask-1
    trigger:
      type: schedule
      frequency: 525600000
    paused: false

resources:
  Resources:
    policies:
      policy-1:
        gas-price-cap: 1000
        whitelist-receivers:
          - "0x0f06aB75c7DD497981b75CD82F6566e3a5CAd8f2"
        eip1559-pricing: true
    notifications:
      test-discord:
        type: discord
        name: morgan-test-discord
        config:
          url: ${self:custom.discordWebhook}
        paused: false
    sentinels:
      forta-multisig-sentinel:
        name: '${self:custom.name} Sentinel'
        type: 'FORTA'
        paused: false
        notify-config:
          timeout: 0
          message: '[TX]({{ metadata.transactionLink }}) {{ metadata.message }}'
          message-subject: 'Defender Sentinel: ${self:custom.name} triggered'
          channels:
            - ${self:resources.Resources.notifications.test-discord}
        conditions:
          min-scanner-count: 1
          severity: 1
        autotask-condition: ${self:functions.autotask-1}
        agent-ids:
          - '0x2e7f036f3495fec41a3eabae03b3efd378f6834bbb2976b99dfed6d3c7de7458'

plugins:
  - defender-serverless
