---
# Custom workflow for running NPM audit
name: NPM Vulnerability Checker
# yamllint disable-line rule:truthy
on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  pull_request:
    branches: [master, main]
    types: [opened, reopened]
  schedule:
    - cron: "0 0 * * 0" # Hours, minutes, day of month, month, day of week. Set for weekly

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      # Looks for package.json in all sub-folders lists all outdated packages for refernce. Ignores error codes.
      - name: List outdated packages
        continue-on-error: true
        # Single command, all newlines are interpreted as a space
        run: >
          find .
          ! -path "*/node_modules/*"
          ! -path "*/additional_path/*"
          -name "package.json"
          -execdir pwd \;
          -execdir npm ci \;
          -execdir npm outdated \;

      # Looks for package.json in all sub-folders and looks for vulnerable packages. Fails on vulnerable packages.
      - name: Check for vulnerabilities
        if: always()
        # Single command, all newlines are interpreted as a space
        run: >
          find . !
          -path "*/node_modules/*"
          ! -path "*/additional_path/*"
          -name "package.json"
          -execdir pwd \;
          -execdir npm audit {} +
